apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://charts.konghq.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kong
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: kong
      version: "2.38.0"
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  targetNamespace: kong
  install:
    createNamespace: true
  values:
    # DB-less mode
    env:
      database: "off"
      router_flavor: "traditional"
    # Enable Ingress Controller
    ingressController:
      enabled: true
      installCRDs: false
    # Proxy service configuration
    proxy:
      type: NodePort
      http:
        enabled: true
        servicePort: 80
        containerPort: 8000
        nodePort: 32080
      tls:
        enabled: true
        servicePort: 443
        containerPort: 8443
        nodePort: 32443
    # Admin API
    admin:
      enabled: true
      type: NodePort
      http:
        enabled: true
        servicePort: 8001
        containerPort: 8001
        nodePort: 32001

