apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  targetNamespace: ingress-nginx
  install:
    createNamespace: true
  values:
    controller:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      hostPort:
        enabled: true
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 90Mi

